import { Account } from "@/lib/auth";

// QR 초대로 가입한 어르신 계정은 비밀번호가 본인이 정한 게 아니라 전화번호 뒷자리
// 4자리로 자동 생성된다(deriveElderBackendPassword, backend-auth.ts). 이름(로그인
// 아이디)과 전화번호를 아는 제3자(택배기사·요양보호사·이웃 등)가 추측하기 쉬운 조합이라
// (2026-08-27 보안 점검), 알림함(notifications.ts의 getElderPasswordSecurityNotice)에서
// 한 번 안내한다. 아직 어르신 본인 토큰으로 비밀번호를 바꿀 수 있는 백엔드 엔드포인트가
// 없어(PATCH /users/{id}는 보호자 토큰만 받음) 안내만 하고 실제로 바꾸는 액션은 없다.

// account.passwordSource === "auto-generated" 플래그(QR초대 동의 화면인 consent-view.tsx가
// registerAccount() 호출 시 남김) 하나만 본다. 한때 이 플래그가 없을 때(크로스디바이스 폴백
// 로그인 — auth.ts의 ensureLocalUserAccount는 백엔드가 전화번호를 안 줘서 이 계정의 진짜
// 출처를 몰라 플래그를 못 남긴다) "phone이 더미값이고 비밀번호가 숫자 4자리인가"로 대신
// 추측했었는데, 직접가입(개인 이용자) 계정도 크로스디바이스 폴백을 타면 로컬 데이터 모양이
// 똑같아져서(phone 더미값 + 우연히 숫자 4자리 비밀번호) 자기가 고른 비밀번호에 "전화번호로
// 자동 생성됐다"는 틀린 문구가 붙는 오탐이 실제 계정에서 확인됐다(2026-08-27, "테스트이용자8814"
// 는 개인이용자인데 걸림). 추측을 얹을수록 다른 방향의 오탐이 계속 나와서, 확실한 플래그가
// 있을 때만 안내하고 없으면 조용히 넘어가는 쪽으로 정리한다.
//
// 알려진 한계: 크로스디바이스 폴백으로 복구된 계정은 원래 QR초대로 가입했어도 이 플래그가
// 없어 안내가 안 뜬다(false negative). 백엔드가 로그인 응답에 "비밀번호 자동생성 여부"를
// 같이 내려주기 전까지는 이 기기 쪽에서 확실히 알 방법이 없다 — 백엔드 지원이 생기면
// 그때 다시 정확하게 잡을 수 있다.
export function isUsingAutoGeneratedPassword(account: Account): boolean {
  return account.role === "user" && account.passwordSource === "auto-generated";
}
